depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple

backbone:
  # [from, number, module, args]
  [[-1, 1, RepVGGBlock, [64, 3, 2]],  # 0-P1/2
   [-1, 1, RepVGGBlock, [128, 3, 2]],  # 1-P2/4
   [-1, 6, RepBlock, [128]],
   [-1, 1, RepVGGBlock, [256, 3, 2]],  # 3-P3/8
   [-1, 12, RepBlock, [256]],
   [-1, 1, RepVGGBlock, [512, 3, 2]],  # 5-P4/16
   [-1, 18, RepBlock, [512]],
   [-1, 1, RepVGGBlock, [1024, 3, 2]],  # 7-P5/32
   [-1, 6, RepBlock, [1024]],
   [-1, 1, SimCSPSPPF, [1024, 5]]]  # 9

neck:
  [[-1, 1, SimConv, [256, 1, 1]], #10
   [[-1, 6, 4], 1, BIC, [256, 256]],
   [-1, 12, RepBlock, [256]],

   [-1, 1, SimConv, [128, 1, 1]], # 13
   [[-1, 4, 2], 1, BIC, [128, 128]],
   [-1, 12, RepBlock, [128]],   #out

   [-1, 1, SimConv, [128, 3, 2]],
   [[-1, 13], 1, Concat, [1]],  # cat head P4
   [-1, 12, RepBlock, [256]],  # 18 (P4/16-medium)

   [-1, 1, SimConv, [256, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 12, RepBlock, [512]]]  # 21 (P5/32-large)

effidehead:
  [[15, 1, Head_layers_fuseab, [128, 0]],#if use_dfl is False, please set reg_max to 0
  [18, 1, Head_layers_fuseab, [256, 0]],
  [21, 1, Head_layers_fuseab, [512, 0]],
  [[22, 23, 24],1,Out, []]]


